obj-$(CONFIG_SND_I2S_HI6210_I2S) += hi6210-i2s.o

# HI6210 Platform Support
snd-soc-hi6210-objs := hi6210_pcm.o
# HI6210-HISSC Machine Support
snd-soc-hi6210-hissc-objs := hi6210_hissc.o
obj-$(CONFIG_SND_SOC_PCM_HI6210) += snd-soc-hi6210.o
obj-$(CONFIG_SND_HI6210_HISSC) += snd-soc-hi6210-hissc.o
snd-soc-hissc-objs := hissc.o
obj-$(CONFIG_SND_SOC_CODEC_HISSC)  += snd-soc-hissc.o
